import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Provider from "./provider";
import Header from "@/components/header";
import { SparklesCore } from "@/components/ui/sparkles";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kapil - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <main className="min-h-dvh md:max-w-[700px] mx-auto w-full flex flex-col items-center justify-start overflow-hidden rounded-md px-4">
            <Header />
            {children}
            <div className="fixed inset-0 -z-10">
              <SparklesCore
                id="tsparticlesfullpage"
                background="transparent"
                minSize={0.6}
                maxSize={1.4}
                particleDensity={40}
                className="w-full h-full"
                particleColor="#FFFFFF"
              />
            </div>
          </main>
        </Provider>
      </body>
    </html>
  );
}
